###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################
sampling_rate: 48000     # Sampling rate.
fft_size: 2048           # FFT size.
hop_size: 512            # Hop size.
win_length: null         # Window length.
                         # If set to null, it will be the same as fft_size.
window: "hann"           # Window function.
num_mels: 80             # Number of mel basis.
fmin: 0                 # Minimum freq in mel basis calculation.
fmax: null               # Maximum frequency in mel basis calculation.
global_gain_scale: 1.0   # Will be multiplied to all of waveform.

feat_list: ["encodec"]
out_feat_type: encodec
prompt_path: /data/group1/z44568r/toolkits2/jatts/egs/hificaptain_jp_female/tts3/dump/eval/feats/Seikatsu01_C-U__000100.h5

###########################################################
#              NETWORK ARCHITECTURE SETTING               #
###########################################################
model_type: ValleNAR
model_params:
    n_tokens: 1024

###########################################################
#                      LOSS SETTING                       #
###########################################################
trainer_type: ValleTrainer
collater_type: ValleCollater
criterions:
    "CFMLoss": {}

###########################################################
#                   INFERENCE SETTING                     #
###########################################################
vocoder:
    vocoder_type: encodec

###########################################################
#                  DATA LOADER SETTING                    #
###########################################################
batch_size: 16              # Batch size.
pin_memory: true            # Whether to pin memory in Pytorch DataLoader.
num_workers: 2              # Number of workers in Pytorch DataLoader.
allow_cache: true           # Whether to allow cache in dataset. If true, it requires cpu memory.

###########################################################
#             OPTIMIZER & SCHEDULER SETTING               #
###########################################################
optimizer_type: Adam
optimizer_params:
    lr: 0.0001
grad_norm: 1.0              # Gradient norm.
scheduler_type: StepLR
scheduler_params:
    step_size: 10000
    gamma: 0.5

###########################################################
#                    INTERVAL SETTING                     #
###########################################################
train_max_steps: 100000     # Number of training steps.
save_interval_steps: 1000   # Interval steps to save checkpoint.
eval_interval_steps: 100    # Interval steps to evaluate the network.
log_interval_steps: 10      # Interval steps to record the training log.

###########################################################
#                     OTHER SETTING                       #
###########################################################
num_save_intermediate_results: 4  # Number of results to be saved as intermediate results.
