###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################
sampling_rate: 24000     # Sampling rate.
fft_size: 2048           # FFT size.
hop_size: 300            # Hop size.
win_length: null         # Window length.
                         # If set to null, it will be the same as fft_size.
window: "hann"           # Window function.
num_mels: 80             # Number of mel basis.
fmin: 80                 # Minimum freq in mel basis calculation.
fmax: 7600               # Maximum frequency in mel basis calculation.
global_gain_scale: 1.0   # Will be multiplied to all of waveform.

feat_list: ["mel", "spkemb"]
out_feat_type: mel

spkemb_extract_type: speechbrain    # speaker embedding extractor type

###########################################################
#              NETWORK ARCHITECTURE SETTING               #
###########################################################
model_type: MatchaTTS_MAS
model_params:
    odim: 80
    adim: 384         # attention dimension
    aheads: 2         # number of attention heads
    elayers: 4        # number of encoder layers
    eunits: 1536      # number of encoder ff units
    positionwise_layer_type: conv1d   # type of position-wise layer
    positionwise_conv_kernel_size: 3  # kernel size of position wise conv layer
    duration_predictor_layers: 2      # number of layers of duration predictor
    duration_predictor_chans: 256     # number of channels of duration predictor
    duration_predictor_kernel_size: 3 # filter size of duration predictor
    use_masking: True                 # whether to apply masking for padded part in loss calculation
    # use_scaled_pos_enc: True          # whether to use scaled positional encoding
    encoder_normalize_before: True    # whether to perform layer normalization before the input
    reduction_factor: 1               # reduction factor
    encoder_type: conformer           # encoder type
    conformer_pos_enc_layer_type: rel_pos        # conformer positional encoding type
    conformer_self_attn_layer_type: rel_selfattn # conformer self-attention type
    conformer_activation_type: swish             # conformer activation type
    use_macaron_style_in_conformer: true         # whether to use macaron style in conformer
    use_cnn_in_conformer: true                   # whether to use CNN in conformer
    conformer_enc_kernel_size: 7                 # kernel size in CNN module of conformer-based encoder
    conformer_dec_kernel_size: 31                # kernel size in CNN module of conformer-based decoder
    init_type: xavier_uniform                    # initialization type
    # init_enc_alpha: 1.0               # initial value of alpha of encoder scaled position encoding
    # init_dec_alpha: 1.0               # initial value of alpha of decoder scaled position encoding
    transformer_enc_dropout_rate: 0.2            # dropout rate for transformer encoder layer
    transformer_enc_positional_dropout_rate: 0.2 # dropout rate for transformer encoder positional encoding
    transformer_enc_attn_dropout_rate: 0.2       # dropout rate for transformer encoder attention layer

    # decoder related
    decoder_channels: [512, 512]
    decoder_dropout: 0.05
    decoder_attention_head_dim: 256
    decoder_n_blocks: 1
    decoder_num_mid_blocks: 2
    decoder_num_heads: 2
    decoder_act_fn: snakebeta

    spk_embed_dim: 192                         # dimension of speaker embedding
    spk_embed_integration_type: add            # how to integrate speaker embedding

###########################################################
#                      LOSS SETTING                       #
###########################################################
trainer_type: MatchaTTSTrainer
collater_type: FastSpeech2Collater
criterions:
    "CFMLoss": {}
    "EncoderPriorLoss": {}
    "ForwardSumLoss": {}
    "DurationPredictorLoss": {}
lambda_align: 2.0

###########################################################
#                   INFERENCE SETTING                     #
###########################################################
vocoder:
    checkpoint: /data/group1/z44476r/Experiments/ParallelWaveGAN/egs/jvs/voc1/exp/train_hifigan.v1/checkpoint-2500000steps.pkl
    config: /data/group1/z44476r/Experiments/ParallelWaveGAN/egs/jvs/voc1/exp/train_hifigan.v1/config.yml
    stats: /data/group1/z44476r/Experiments/ParallelWaveGAN/egs/jvs/voc1/exp/train_hifigan.v1/stats.h5
temperature: 0.667
ode_steps: 10

###########################################################
#                  DATA LOADER SETTING                    #
###########################################################
batch_size: 16              # Batch size.
pin_memory: true            # Whether to pin memory in Pytorch DataLoader.
num_workers: 2              # Number of workers in Pytorch DataLoader.
allow_cache: true           # Whether to allow cache in dataset. If true, it requires cpu memory.

###########################################################
#             OPTIMIZER & SCHEDULER SETTING               #
###########################################################
optimizer_type: Adam
optimizer_params:
    lr: 0.0001
grad_norm: 1.0              # Gradient norm.
scheduler_type: StepLR
scheduler_params:
    step_size: 10000
    gamma: 0.5

###########################################################
#                    INTERVAL SETTING                     #
###########################################################
train_max_steps: 100000     # Number of training steps.
dp_train_start_steps: 10000 # Duration predictor training starting step. Default set to 0.
bin_loss_start_steps: 15000 # Duration predictor training starting step. Default set to 0.
save_interval_steps: 5000   # Interval steps to save checkpoint.
eval_interval_steps: 500    # Interval steps to evaluate the network.
log_interval_steps: 10      # Interval steps to record the training log.

###########################################################
#                     OTHER SETTING                       #
###########################################################
num_save_intermediate_results: 4  # Number of results to be saved as intermediate results.
